//Variables
@url = localhost:3001
@expiryTime =U2FsdGVkX18mlH4w5n5rs6531WmBseynPvwVN0RtYSLBkxEBiwXO8ODmAr1hjLmGPor21LdHlPDCzoLI0KXbpL7xMl3JkHJWAMl32%3D
@encryptedUser = U2FsdGVkX1Por21LdIVJlotkUeLRxMl3JkRIN6rKmAtxqr7lK0hQoYXzhgwH2FrRH0RSI4o0YZA@vimToken = "e85ba2c94efa296889a175b8e56fcf33"
####
//add new route
POST http://{{url}}/api/traffRoute/new
content-type: application/json

{
    "to": "אריאל",
    "from": "מחלף אורנית (שער השומרון)",
    "type": "waze",
    "wazeUrl":"https://www.waze.com/he/live-map/directions/%D7%90%D7%A8%D7%99%D7%90%D7%9C?to=place.ChIJ6_6XBwsnHRURrbo12csDrug&from=place.w.22937921.229379211.7598"
}
####

//Get avg
POST http://{{url}}/api/traffRoute/avg
content-type: application/json

{
    "route":"63baa83c06b795747ea8f262"

}

####
    # "createdAt":{"$gte":
    # "2023-01-01T00:00:00+02:00","$lt":"2023-01-09T23:59:59+02:00"
    # }
//Update route
POST http://{{url}}/api/traffRoute/update/144
content-type: application/json

{
    "avgByDays":{
    "0": {
      "0": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "1": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "2": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "3": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "4": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "5": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "6": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "7": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "8": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "9": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "10": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "11": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "12": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "13": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "14": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "15": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "16": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "17": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "18": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "19": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "20": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "21": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "22": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "23": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      }
    },
    "1": {
      "0": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "1": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "2": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "3": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "4": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "5": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "6": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "7": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "8": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "9": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "10": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "11": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "12": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "13": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "14": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "15": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "16": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "17": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "18": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "19": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "20": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "21": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "22": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "23": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      }
    },
    "2": {
      "0": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "1": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "2": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "3": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "4": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "5": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "6": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "7": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "8": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "9": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "10": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "11": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "12": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "13": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "14": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "15": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "16": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "17": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "18": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "19": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "20": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "21": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "22": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "23": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      }
    },
    "3": {
      "0": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "1": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "2": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "3": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "4": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "5": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "6": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "7": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "8": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "9": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "10": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "11": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "12": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "13": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "14": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "15": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "16": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "17": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "18": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "19": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "20": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "21": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "22": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "23": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      }
    },
    "4": {
      "0": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "1": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "2": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "3": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "4": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "5": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "6": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "7": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "8": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "9": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "10": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "11": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "12": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "13": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "14": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "15": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "16": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "17": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "18": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "19": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "20": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "21": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "22": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "23": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      }
    },
    "5": {
      "0": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "1": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "2": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "3": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "4": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "5": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "6": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "7": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "8": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "9": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "10": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "11": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "12": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "13": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "14": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "15": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "16": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "17": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "18": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "19": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "20": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "21": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "22": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "23": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      }
    },
    "6": {
      "0": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "1": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "2": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "3": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "4": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "5": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "6": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "7": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "8": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "9": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "10": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "11": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "12": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "13": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "14": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "15": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "16": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "17": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "18": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "19": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "20": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "21": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "22": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      },
      "23": {
        "1": null,
        "2": null,
        "3": null,
        "4": null,
        "hourAvg": null
      }
    }
  }
}
